### ISSUE TITLE
[BUG]: Some brokers are not showing up in broker display addons

### ISSUE THREAD

**Issue by 4C51** [HizurosWoWAddOns/Broker_Everything#15]
### WoW client

WoW Retail

### What happened?

These modules are showing up:
- Achievements
- Bags
- Calendar
- Currency
- Durability
- Equipment
- Guild
- Guild log
- IDs
- Location
- Quest Log
- Raids
- Reputation
- Surprise
- Tracking
- Volume
- WoW Token
- XP
- ZoneText

These modules do not show up:
- Appearances
- Chat Channels
- Class specs
- Dungeons
- Emissary Quests
- Followers
- Friends
- Game Menu
- Garrison
- Gold
- GPS
- Latency
- Mail
- Memory
- Missions
- Nameplates
- Notes
- Order hall
- Professions
- Ships
- Speed
- Stuff
- System
- Tanaan Jungle Dailies
- Traffic

(I may have missed some)

For any of the malfunctioning ones, I can go into Enable/Disable modules in the Broker_Everything options and disable and then reenable twice and it will show up in the broker display until the UI is reloaded, then it returns to an error state.

No errors are generated except for some modules that have errors loading (e.g. nameplates)

### Other addons?

Using ChocolateBar
Also tested with NinjaPanel to check if it was having the same issue seeing certain modules, it was.

**Comment by Calathan198** [comment]
It's the same with Bazooka as well

**Comment by hizuro** [comment]
Thank you for reporting. Please try version 4.4.1.

**Comment by 4C51** [comment]
Fixed in 4.4.2!
