### ISSUE TITLE
[BUG]: 10.0 Click on transport with any hearthstone not working

### ISSUE THREAD

**Issue by agentschmitt** [HizurosWoWAddOns/Broker_Everything#17]
### WoW client

WoW Retail

### What happened?

right click on zonetext broker 
left click on hearthstone (or any other transport)
current result:
-> lua error on highlight
-> no action on click

i found some workaround fixes:

change shared.lua line 772 to fix hightlight
from: sbf:SetHighlightTexture([[interface\friendsframe\ui-friendsframe-highlightbar-blue]], true);
to: sbf:SetHighlightTexture([[interface\friendsframe\ui-friendsframe-highlightbar-blue]]);

add shared.lua one line 773 to fix click
sbf:RegisterForClicks("AnyUp", "AnyDown")

### Lua Error Message?

```lua
1x bad argument #3 to '?' (Usage: self:SetHighlightTexture(asset [, blendMode]))
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/Broker_Everything/shared.lua"]:772: in function `secureButton'
[string "@Interface/AddOns/Broker_Everything/modules/gps.lua"]:310: in function `_OnEnter_func'
[string "@Interface/AddOns/BagSync/libs/LibQTip-1.0-49/LibQTip-1.0.lua"]:1337: in function <...face/AddOns/BagSync/libs/LibQTip-1.0/LibQTip-1.0.lua:1331>

Locals:
(*temporary) = "bad argument #3 to '?' (Usage: self:SetHighlightTexture(asset [, blendMode])
```

### Other addons?

i am using 100+ addons so maybe not worth to list them all :P
as databroker display i am using bazooka

**Comment by hizuro** [comment]
Thank you for reporting. Please try version 4.4.1.
