### ISSUE TITLE
[BUG]: Mute Volume in Retail Version 10.0.0 (46455)

### ISSUE THREAD

**Issue by XIIIFaces** [HizurosWoWAddOns/Broker_Everything#21]
### WoW client

WoW Retail

### What happened?

Clicking on the volume control to mute the game puts out an error and nothing else happens.
Allready deleted the titanpanel volume control addon to avoid overlapping.

### Lua Error Message?

```lua
Message: ...nterface/AddOns/Broker_Everything/modules/volume.lua:307: attempt to call global 'BlizzardOptionsPanel_GetCVarSafe' (a nil value)
Time: Fri Nov  4 13:02:00 2022
Count: 6
Stack: ...nterface/AddOns/Broker_Everything/modules/volume.lua:307: attempt to call global 'BlizzardOptionsPanel_GetCVarSafe' (a nil value)
[string "=[C]"]: in function `BlizzardOptionsPanel_GetCVarSafe'
[string "@Interface/AddOns/Broker_Everything/modules/volume.lua"]:307: in function `func'
[string "@Interface/AddOns/Broker_Everything/shared.lua"]:1961: in function `func'
[string "@Interface/AddOns/Broker_Everything/modules.lua"]:69: in function <Interface/AddOns/Broker_Everything/modules.lua:68>
[string "@Interface/AddOns/Titan/LDBToTitan.lua"]:290: in function <Interface/AddOns/Titan/LDBToTitan.lua:288>

Locals:
```

### Other addons?

Using the Broker in titanpanel.

**Comment by nancikennedy** [comment]
I experienced an issue that might be related. While logged in to the game and away from my computer, my energy savings kicked in and the monitor/sound turned off. Woke it up and found that are error was thrown as a result:

2x ...nterface/AddOns/Broker_Everything/modules/volume.lua:52: bad argument #1 to 'format' (number expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface/AddOns/Broker_Everything/modules/volume.lua"]:52: in function <...nterface/AddOns/Broker_Everything/modules/volume.lua:51>
[string "@Interface/AddOns/Broker_Everything/modules/volume.lua"]:366: in function <...nterface/AddOns/Broker_Everything/modules/volume.lua:358>

Locals:
(*temporary) = "%.2f"
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by XIIIFaces** [comment]
Got fixed, thanks a lot !!!
