### ISSUE TITLE
[BUG]: GetContainerItemLink error

### ISSUE THREAD

**Issue by nancikennedy** [HizurosWoWAddOns/Broker_Everything#22]
### WoW client

WoW Retail

### What happened?

Doing various things with inventory items....caused no doubt by GetContainerItemLink being superseded by C_Container.GetContainerItemLink	

### Lua Error Message?

```lua
9x Broker_Everything/shared.lua:1119: attempt to call upvalue 'GetContainerItemLink' (a nil value)
[string "@Broker_Everything/shared.lua"]:1119: in function <Broker_Everything/shared.lua:1117>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Sorted/Utilities.lua"]:831: in function `VendorTrash'
[string "@Sorted/FrameBuilder.lua"]:1172: in function <Sorted/FrameBuilder.lua:1171>

Locals:
bag = 0
slot = 3
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 0
(*temporary) = 3
(*temporary) = "attempt to call upvalue 'GetContainerItemLink' (a nil value)"
tonumber = <function> defined =[C]:-1
GetContainerItemLink = nil
callback = <table> {
 128294 = <table> {
 }
}
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
```

**Comment by Nillx** [comment]
Yep im getting this error too after 10.0.2

**Comment by jisamcom** [comment]
change line 16 of shared.lua

local GetContainerItemCooldown,GetContainerItemLink=C_Container.GetContainerItemCooldown,C_Container.GetContainerItemLink;

**Comment by Nillx** [comment]
Thanks, that fixed the error

**Comment by VaporAPX** [comment]
Doing this stops the LUA error, but it causes stutter when vendoring or interacting with items in your inventory. Disabling the addon corrects the issue.

**Comment by fraerie** [comment]
Also getting this

```
349x Interface/AddOns/Broker_Everything/shared.lua:1119: attempt to call upvalue 'GetContainerItemLink' (a nil value)
[string "@Interface/AddOns/Broker_Everything/shared.lua"]:1119: in function <Interface/AddOns/Broker_Everything/shared.lua:1117>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

Locals:
bag = 4
slot = 10
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 4
(*temporary) = 10
(*temporary) = "attempt to call upvalue 'GetContainerItemLink' (a nil value)"
tonumber = <function> defined =[C]:-1
GetContainerItemLink = nil
callback = <table> {
 163320 = <table> {
 }
 162131 = <table> {
 }
 162139 = <table> {
 }
 166368 = <table> {
 }
 137774 = <table> {
 }
 162352 = <table> {
 }
 162376 = <table> {
 }
 162132 = <table> {
 }
 162361 = <table> {
 }
 163314 = <table> {
 }
 162377 = <table> {
 }
 162133 = <table> {
 }
 142107 = <table> {
 }
 162023 = <table> {
 }
 182668 = <table> {
 }
 162129 = <table> {
 }
 183098 = <table> {
 }
 162134 = <table> {
 }
 162256 = <table> {
 }
 162289 = <table> {
 }
 137777 = <table> {
 }
 162292 = <table> {
 }
 162363 = <table> {
 }
 163316 = <table> {
 }
 183106 = <table> {
 }
 162135 = <table> {
 }
 162287 = <table> {
 }
 162128 = <table> {
 }
 162288 = <table> {
 }
 162293 = <table> {
 }
 183102 = <table> {
 }
 183104 = <table> {
 }
 162254 = <table> {
 }
 162136 = <table> {
 }
 166806 = <table> {
 }
 183103 = <table> {
 }
 137779 = <table> {
 }
 166263 = <table> {
 }
 142331 = <table> {
 }
 163318 = <table> {
 }
 162255 = <table> {
 }
 162137 = <table> {
 }
 162371 = <table> {
 }
 162373 = <table> {
 }
 137780 = <table> {
 }
 162358 = <table> {
 }
 183093 = <table> {
 }
 182660 = <table> {
 }
 162130 = <table> {
 }
 162138 = <table> {
 }
 166367 = <table> {
 }
 137773 = <table> {
 }
 137781 = <table> {
 }
 162359 = <table> {
 }
 142120 = <table> {
 }
}
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
```

**Comment by tatatada** [comment]
338x Broker_Everything/shared.lua:1119: attempt to call upvalue 'GetContainerItemLink' (a nil value)
[string "@Broker_Everything/shared.lua"]:1119: in function <Broker_Everything/shared.lua:1117>
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

Locals:
bag = 4
slot = 7
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 4
(*temporary) = 7
(*temporary) = "attempt to call upvalue 'GetContainerItemLink' (a nil value)"
tonumber = <function> defined =[C]:-1
GetContainerItemLink = nil
callback = <table> {
 162287 = <table> {
 }
 142331 = <table> {
 }
 162706 = <table> {
 }
 123951 = <table> {
 }
 123953 = <table> {
 }
 123955 = <table> {
 }
 162288 = <table> {
 }
 162292 = <table> {
 }
 162707 = <table> {
 }
 162289 = <table> {
 }
 183094 = <table> {
 }
 182668 = <table> {
 }
 123948 = <table> {
 }
 162708 = <table> {
 }
 162774 = <table> {
 }
 123954 = <table> {
 }
 166368 = <table> {
 }
 162293 = <table> {
 }
 183095 = <table> {
 }
 166263 = <table> {
 }
 166806 = <table> {
 }
 166367 = <table> {
 }
 136698 = <table> {
 }
 136697 = <table> {
 }
}
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1

**Comment by tatatada** [comment]
115x Broker_Everything/shared.lua:1216: attempt to call upvalue 'GetContainerItemLink' (a nil value)
[string "@Broker_Everything/shared.lua"]:1216: in function <Broker_Everything/shared.lua:1186>
[string "=(tail call)"]: ?
[string "@Broker_Everything/modules/durability.lua"]:90: in function `fnc'
[string "@Broker_Everything/shared.lua"]:813: in function <Broker_Everything/shared.lua:807>
[string "@Broker_Everything/shared.lua"]:842: in function <Broker_Everything/shared.lua:817>
[string "@Broker_Everything/shared.lua"]:998: in function <Broker_Everything/shared.lua:938>
[string "@Broker_Everything/shared.lua"]:1024: in function <Broker_Everything/shared.lua:1012>

Locals:
tt = Broker_EverythingScanTooltip2 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 CIMI_tooltipWritten = true
 hasMoney = 1
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 shownMoneyFrames = 168
 numMoneyFrames = 168
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 info = <table> {
 }
 shouldRefreshData = true
 updateTooltipTimer = 0
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = Broker_EverythingScanTooltip2StatusBar {
 }
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @CompactVendorFilter/frame.lua:143
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = Broker_EverythingScanTooltip2TextRight1 {
 }
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @CompactVendorFilter/frame.lua:137
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 S

**Comment by fraerie** [comment]
still seeing this error in retail every session. not sure if anyone is looking for a fix.
