### ISSUE TITLE
[BUG]: Repair/durability  module causing FPS stutters

### ISSUE THREAD

**Issue by Nillx** [HizurosWoWAddOns/Broker_Everything#23]
### WoW client

WoW Retail

### What happened?

It seems the repair module is causing FPS stutters after awhile (1-2 dungeons and the game starts stuttering when im in combat. Reload fixes the issue for a bit). This started happening after 10.0.0 but got way worse after 10.0.2

Noticed that Titan Panel is having the same issue and they are rewriting the repair/durability module.

### Lua Error Message?

```lua
There are no lua errors. Bugsack + Buggrabber show no errors while my game is stuttering.
```

### Other addons?

Im using this addon combined with Bazooka.

**Comment by agentschmitt** [comment]
@Nillx i assume that this could be related to the tooltip scanning creating frames which has now another solution in wow 10.0.2 https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes#Tooltip_Changes
i created pr #24 to make usage of the new api and hopefully it removes lags, but did no dungeon run for testing yet.

**Comment by Nillx** [comment]
Someone posted this comment on curse

`You can replicate the issue by opening your bag and switching an item over and over, after around 10 switches each new switch will micro-freeze the game and it gets worse and worse until you /reload. (I debuged this on a capital city, not sure if matters but just as info)`

**Comment by agentschmitt** [comment]
@Nillx thanks for that info, i can reproduce it with switching item in capital city too, when the item has less then 100% durability, as only then we get some tooltip scanning to determine the costs. This causes massive lags after some switches.

With the new tooltip scanning it lags a bit during the switches, but afterwards my fps is stable again.
But a dungeon test would still be good, as i am not sure if update of durability in dungeon will cause some fps drop still.

**Comment by Nillx** [comment]
Im currently using this addon as a replacement and there are no issues with it. https://www.curseforge.com/wow/addons/zz_repair

**Comment by Spiderkeg** [comment]
Thank you very much for pinpointing as to why my game stutters after awhile.  I couldn't figure what the issue was.

**Comment by Nillx** [comment]
Yeah it took me 2 weeks ot disabling addons, reinstalling the game, replacing addons until i saw a post on titan panel mentioning this isue...

**Comment by hizuro** [comment]
I've uploaded 4.4.4-beta for testing.
Include changes of durability module. I hope it remove the fps probem.
Sorry for the inconvenience.


greetings Hizuro

**Comment by agentschmitt** [comment]
@hizuro i tested 4.4.4-beta yesterday during an instance run and it looked better now.
I accidently updated to 4.4.3 before an instance run and had lags, but after updating to 4.4.4-beta they were gone.

But i am still not sure if any other module then repair, could cause fps issues when they use the old tooltip scanning by creating frames instead of using new api from wow 10.0.2. see https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes#Tooltip_Changes
I also made a pr for this api changes: https://github.com/HizurosWoWAddOns/Broker_Everything/pull/24
