### ISSUE TITLE
[BUG]: Ammo module not working in 3.4.1

### ISSUE THREAD

**Issue by kazso** [HizurosWoWAddOns/Broker_Everything#32]
### WoW client

WoW Classic WotLk

### What happened?

Logging into a hunter character i get an error, and the ammo tooltip is empty since patch 3.4.1.

I came up with a temporary solution until this is fixed.
Changing
`local _, count = GetContainerItemInfo(item.bag,item.slot);`
to
`local count = (C_Container.GetContainerItemInfo(item.bag,item.slot)).stackCount;`
in **ammo_classic.lua** works for me (no errors and shows the correct amount of ammo). Only tested this in WotLK Classic.

### Lua Error Message?

```lua
2x ...ceBroker_Everything/modules/ammo_classic.lua:68: attempt to call global 'GetContainerItemInfo' (a nil value)
[string "@Broker_Everything/modules/ammo_classic.lua"]:68: in function `fnc'
[string "@Broker_Everything/shared.lua"]:826: in function <Broker_Everything/shared.lua:821>
[string "@Broker_Everything/shared.lua"]:855: in function <Broker_Everything/shared.lua:830>
[string "@Broker_Everything/shared.lua"]:1005: in function <Broker_Everything/shared.lua:948>
[string "@Broker_Everything/shared.lua"]:1031: in function <Broker_Everything/shared.lua:1019>
```

**Comment by hizuro** [comment]
Thank you for reporting.
Update is available.
