### ISSUE TITLE
[BUG]: Massive stuttering in 10.1

### ISSUE THREAD

**Issue by csutcliff** [HizurosWoWAddOns/Broker_Everything#38]
### WoW client

WoW Retail

### What happened?

Hi, Since 10.1 this is causing massive stuttering, a full freeze frame every second or so. No LUA errors and it doesn't show high CPU usage in an addon profiler so I'm not sure how to narrow it down. It goes away entirely when disabling the addon. It feels similar to the issue in #23 a little while ago.

### Other addons?

I've tried with only this + bazooka enabled, same result.

**Comment by Nillx** [comment]
This is happening to me aswell, no LUA errors only stutters.

**Comment by Saxayone** [comment]
Seems to be related to the Memory module, it was showing no data so I assumed that was probably the cause of the stutter since it would be running every few seconds to try and gather the info > having an issue.

Disabling that module stopped the stuttering for me.

**Comment by steven-fuller** [comment]
I am also seeing new stutters since 10.1.
I am currently only using Gold, Speed, System, and Volume modules.
I can eliminate the stuttering by disabling the 'Memory usage' option under System -> Tooltip

**Comment by hizuro** [comment]
please try version 4.5.9-beta2

**Comment by Nillx** [comment]
My game no longer stutter with that version but im getting a lot of XML errors plus there are <> around the names of the options 
![image](https://user-images.githubusercontent.com/34476875/236288953-2977b60e-568d-44e3-8cf3-a81db26fc754.png)
![image](https://user-images.githubusercontent.com/34476875/236289086-c827f712-44ba-49e9-96a6-077046354c33.png)

**Comment by Saxayone** [comment]
Version 4.5.9-beta2 fixes the stuttering for me without the other errors.
