### ISSUE TITLE
Ammo display not working in TBCC

### ISSUE THREAD

**Issue by kazso** [HizurosWoWAddOns/Broker_Everything#4]
Ammo module is not working in TBCC ("No ammo attached"), because the client version check in **shared.lua** only passes for Classic and Classic SoM (which are v1 clients).
To fix this, the lines
```
		if ns.client_version<2 then
			if info.ammo then
				ammo[info.sharedSlot] = true;
				hasChanged.ammo = true;
			end
			-- souls?
		end
```
should be
```
		if ns.client_version<4 then
			if info.ammo then
				ammo[info.sharedSlot] = true;
				hasChanged.ammo = true;
			end
			-- souls?
		end
```
For TBCC less than 3 would suffice, but with the WotLKC release it would break again. That's why I suggest to check it for less than 4.
Ammo was removed in Cataclysm, so the version check can stay at <4 forever. V4.x client would be Cataclysm Classic (if that would be released in the future).

**Comment by hizuro** [comment]
Thank you for reporting. Update coming soon.
