### ISSUE TITLE
Error since 10.2.6

### ISSUE THREAD

**Issue by zaphon** [HizurosWoWAddOns/Broker_Everything#44]
Since 10.2.6 launched I'm getting an error on this line below. And looking through the code, I'm not even sure how it worked in 10.2.5 as from what I can tell itemsByID is an array of arrays (by ID as the main array and by sharedSlot as the second array). But this section of code is pulling the array by ID and than trying to reference info.link which is NIL and throws an error (as nothing is ever assigned at this level).

https://github.com/HizurosWoWAddOns/Broker_Everything/blob/8e01acfebb0216a3f92f895b98618f1004bb8c1d/shared.lua#L1133

**Comment by NoShotz** [comment]
Yep, getting this too.

**Comment by PedjaSenpai** [comment]
Commit is not solving the issue just introduce more lua later down the line

Broker_Everything/shared.lua:1137: attempt to index field '?' (a nil value)
[string "@Broker_Everything/shared.lua"]:1137: in function <Broker_Everything/shared.lua:1121>
