### ISSUE TITLE
New currencies in DF Season 4

### ISSUE THREAD

**Issue by Ale-wants-coffee** [HizurosWoWAddOns/Broker_Everything#47]
https://github.com/HizurosWoWAddOns/Broker_Everything/blob/e7b146dee5600e17b461ff8f91e7da9762753537/modules/currency.lua#L600

replace with 		`"EXPANSION_NAME9",2806,2807,2809,2812,2777,2650,2651,2594,2245,2118,2003,2122,2045,2011,2134,2105,"prof:k:9:1","prof:k:9:2","prof:w:9:1","prof:w:9:2",
`

**Comment by hizuro** [comment]
Thank you for reporting.
Update coming soon.
