### ISSUE TITLE
[FEATURE]: Broker Translocation Matrix

### ISSUE THREAD

**Issue by Aes-Seda** [HizurosWoWAddOns/Broker_Everything#6]
### Description

The New Toy : Broker Translocation Matrix is not included in the [gps.lua] module
It is the new Hearth Stone Toy you get from The Elightened - Exalted for  $5,000 gold.

Can you please add this Item.
I believe this is the correct ID number: 190237/broker-translocation-matrix

please check if this is correct 
I got this from Wowhead site. 

 
Thanks In Advance

### Additional Information

Forgive me it you got a message from CurseForge.

**Comment by hizuro** [comment]
Thank you for reporting. Update coming soon.
